### ISSUE TITLE
radish-test does not match enums

### ISSUE THREAD

**Issue by fliiiix** [radish-bdd/radish#478]
It's not possible to match enums with the step matcher this is the closest i got.

```
class CanType(IntEnum):
    CAN = 0
    CANFD = 1

@custom_type("CanType", r"(Can|CanFD)")
def parse_type(text):
    if text == "Can":
        return CanType.CAN
    if text == "CanFD":
        return CanType.CANFD
    return None


@step("I send a {cantype:CanType} message {msg:QuotedString}")
def send_can_message(step, cantype, msg):
```

test

```
- sentence: I send a Can message "[0x25, 0x5A, 0xFF]"
  should_match: send_can_message
  with_arguments:
      - cantype:
            type: CanType
            value: 0
            use_repr: True
      - msg: "[0x25, 0x5A, 0xFF]"
```

with the result

```
89: >> STEP "I send a Can message "[0x25, 0x5A, 0xFF]"" SHOULD MATCH send_can_message    ✘ (at /home/niederbf/work/simulacrum/build/share/radish/steps_vcan.py:48)
89:   - Expected argument "cantype" with value "0" does not match value "0"
```
